#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "digisteps"
name = "Digisteps"
description.en = "Create simple online educational pathes"
description.fr = "Créer des parcours pédagogiques simples en ligne"

version = "0.6.4~ynh1"

maintainers = ["Pierre-Amiel Giraud"]

[upstream]
license = "GPL-3.0-only"
website = "https://ladigitale.dev/"
demo = "https://ladigitale.dev/digisteps/#/"
admindoc = "https://codeberg.org/ladigitale/digisteps/src/branch/master/README.md"
userdoc = "https://ladigitale.dev/blog/digisteps-pour-creer-des-parcours-pedagogiques-en-ligne"
code = "https://codeberg.org/ladigitale/digisteps"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/digisteps"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://codeberg.org/ladigitale/digisteps/archive/0.6.4.tar.gz"
    sha256 = "7d2e33eb740d2c1a461e7d5b300e87b7077a895f7ac87f07ec261ec575371abc"
    autoupdate.strategy = "latest_forgejo_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-sqlite3, php8.2-gd"
