packaging_format = 2

id = "digisteps"
name = "Digisteps"
description.en = "Create simple online educational pathes"
description.fr = "Créer des parcours pédagogiques simples en ligne"

version = "0.5.15~ynh1"

maintainers = ["Pierre-Amiel Giraud"]

[upstream]
license = "GPL-3.0-only"
website = "https://ladigitale.dev/"
demo = "https://ladigitale.dev/digisteps/#/"
admindoc = "https://codeberg.org/ladigitale/digisteps/src/branch/master/README.md"
userdoc = "https://ladigitale.dev/blog/digisteps-pour-creer-des-parcours-pedagogiques-en-ligne"
code = "https://codeberg.org/ladigitale/digisteps"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/digisteps"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://codeberg.org/ladigitale/digisteps/releases/download/0.5.15/digisteps-v0.5.15.zip"
        sha256 = "d367e32ac8044b98c630b8a4c86ab1a2b6217e16db4e3cbab523020c2efae5b5"
        autoupdate.strategy = "latest_forgejo_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-sqlite3, php8.2-gd"
