test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.0d3c5e6bc951ba9a6a738e3bd55e7fdff1956632.name = "Upgrade from 0.3.4"
